### ISSUE TITLE
Login and Sign up buttons appear grayed out

### ISSUE THREAD

**Issue by ghobs91** [Denarri/Android-Issue-Tracker#9]
I imagine this would confuse users, as grayed out buttons usually indicates that it's disabled.

**Comment by bidluo** [comment]
Hmm this one is a hard one since I can't modify the parse login ui library anymore since I've switched over to using the gradle builds (similar to cocoapods with XCode I guess).

**Comment by bidluo** [comment]
Scratch that, the samples they provided have some sort of workaround
